TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_TAB
    TAP: KEY_TAB
    HOLD: KEY_LEFTMETA
  - KEY: KEY_BACKSLASH
    TAP: KEY_BACKSLASH
    HOLD: KEY_LEFTMETA
