11111theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %B %d, %Y : %R"
