icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#BD93F9"
info_bg = "#282A36"
info_fg = "#8BE9FD"
good_bg = "#282A36"
good_fg = "#50FA7B"
warning_bg = "#282A36"
warning_fg = "#F1FA8C"
critical_bg = "#282A36"
critical_fg = "#FF5555"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "music"
buttons = ["play", "next"]
max_width = 50

[[block]]
block = "bluetooth"
mac = "78:DB:2F:DF:48:78"
label = "AnnePro2"

[[block]]
block = "bluetooth"
mac = "4C:87:5D:C9:56:56"
label = "QC-35"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %b %d, %R"
