icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#F8F8F2"
info_bg = "#BD93F9"
info_fg = "#F8F8F2"
good_bg = "#50FA7B"
good_fg = "#F8F8F2"
warning_bg = "#F1FA8C"
warning_fg = "#F8F8F2"
critical_bg = "#FF5555"
critical_fg = "#F8F8F2"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %B %d, %Y : %R"
