icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#BD93F9"
info_bg = "#282A36"
info_fg = "#8BE9FD"
good_bg = "#282A36"
good_fg = "#50FA7B"
warning_bg = "#282A36"
warning_fg = "#F1FA8C"
critical_bg = "#282A36"
critical_fg = "#FF5555"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "music"
buttons = ["play", "next"]
max_width = 50

[[block]]
block = "bluetooth"
mac = "78:DB:2F:DF:48:78"
label = "AnnePro2"

[[block]]
block = "bluetooth"
mac = "4C:87:5D:C9:56:56"
label = "QC-35"

[[block]]
block = "net"
device = "wlp1s0"
device = "enp3s0"
ssid = true
signal_strength = false
ip = false
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 5
use_bits = false
hide_missing = true
hide_inactive = false

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "XXX", city_id = "1264527", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %b %d, %R"
