#!/usr/bin/env sh

function unmount_usb() {
    mount_path="/run/media/$USER/"
    path_to_unmount=$(exa -1d $mount_path/* | rofi -dmenu -i -p "Unmount Path > ")
    udiskie-umount "$path_to_unmount"
}

function mount_mtp() {
    mount_path="/tmp/$USER/"
    device_to_mount=$(simple-mtpfs -l | rofi -dmenu -i -p "Mount Device > ")
    device_id=$(echo "${device_to_mount}"| cut -d':' -f 1)
    device_name=$(echo "${device_to_mount}"| awk -F' ' '{for (i=2; i<=NF; i++) print $i}' | paste -sd " ")
    device_mount_path="${mount_path}${device_name}"
    mkdir -p "${device_mount_path}"
    simple-mtpfs --device "${device_id}" "${device_mount_path}"
}

function unmount_mtp() {
    mount_path="/tmp/$USER/"
    path_to_unmount=$(exa -1d $mount_path/* | rofi -dmenu -i -p "Unmount Device > ")
    fusermount -u "$path_to_unmount"
    fusermount_exit=$?
    if [[ $fusermount_exit -eq 0 ]]
    then
        rmdir "${path_to_unmount}"
    fi
}

menu=$(echo -e "1. Unmount USB\n2. Mount MTP\n3. Unmount MTP" | rofi -dmenu -i -p "Mount/Unmount > ")
case "${menu}" in
    "1. Unmount USB") unmount_usb;;
    "2. Mount MTP") mount_mtp;;
    "3. Unmount MTP") unmount_mtp;;
esac
