#!/usr/bin/env sh

arg="$1"
amount="$2"

mute_unmute() {
    pamixer -t
}

inc_volume() {
    pamixer -i $1
}

dec_volume() {
    pamixer -d $1
}

case $arg in
    "mute") mute_unmute ;;
    "inc") inc_volume $amount ;;
    *) dec_volume $amount ;;
esac
