icons = "awesome"

[theme]
name = "gruvbox-dark"

[[block]]
block = "nvidia_gpu"
label = "GTX 970"
show_utilization = false
show_memory = false
show_clocks = false
show_fan_speed = true
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min} min, {max} max, {average} avg"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "b48b161466fed0c120a279c4819c1e47", city_id = "1264527", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %b %d, %R"
