icons = "awesome"

[theme]
name = "gruvbox-dark"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min} min, {max} max, {average} avg"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "XXX", city_id = "1264527", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a, %b %d, %R"
